In [36]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [38]:
randomNo = np.random.random((3,3,3))
print(randomNo)

[[[0.63260132 0.5292164  0.22706582]
  [0.15264553 0.3345823  0.13314098]
  [0.49898896 0.46955566 0.29943088]]

 [[0.94877866 0.5833975  0.11515015]
  [0.31916122 0.52261707 0.46892668]
  [0.8600634  0.98138176 0.15456157]]

 [[0.10840886 0.80092846 0.27562587]
  [0.29302927 0.03727632 0.43830548]
  [0.94747208 0.17958035 0.63875154]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [15]:
digM=np.diag(1+np.arange(4), k = -1)
print(digM)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [13]:
cb=np.zeros((8,8),dtype=int)
cb[1::2, ::2]=1
cb[::2,1::2] =1
print (cb)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [29]:
normNO = np.random.random((5,5))
print("Original Array\n",normNO)
maxno, minno = normNO.max(), normNO.min()

normNO= (normNO-Zmin)/(maxno-minno)  
print("Normalize Array\n",normNO)

Original Array
 [[0.01383819 0.77573984 0.19561638 0.33414142 0.81817227]
 [0.22739694 0.09728499 0.12488547 0.98563776 0.10736427]
 [0.73837938 0.90995708 0.9064995  0.44194782 0.32308166]
 [0.89228607 0.83528512 0.73905936 0.07293293 0.06991089]
 [0.56661754 0.65181707 0.75891915 0.35398607 0.59706812]]
Normalize Array
 [[0.01031962 0.79433072 0.19737279 0.33991766 0.83799448]
 [0.23007558 0.09618794 0.12458936 1.01031962 0.10655972]
 [0.75588611 0.93244277 0.92888487 0.45085247 0.32853696]
 [0.91425898 0.85560393 0.75658582 0.07112922 0.06801948]
 [0.57913995 0.66681186 0.77702191 0.36033817 0.61047416]]


# 5.  How to find common values between two arrays?

In [40]:
firstA = np.array([1,2,3,4,5])
print("First array :",firstA)
secondA = [3,5,4,2,0,9]
print("Second array:",secondA)
print("Common values between two arrays are:")
print(np.intersect1d(firstA, secondA))

First array : [1 2 3 4 5]
Second array: [3, 5, 4, 2, 0, 9]
Common values between two arrays are:
[2 3 4 5]


# 6.How to get the dates of yesterday, today and tomorrow?

In [42]:
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print("Yesterday's Date:",yesterday)
today=np.datetime64('today','D')
print("Today's Date:",today)
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("Tomorrow's Date:",tomorrow)

Yesterday's Date: 2020-07-25
Today's Date: 2020-07-26
Tomorrow's Date: 2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [46]:
A = np.random.randint(0,5,7)
print("Array A:",A)
B = np.random.randint(0,5,7)
print("Array B:",B)
equal = np.array_equal(A,B)
print("Check if array's values are equal:",equal)

Array A: [4 0 2 4 0 2 4]
Array B: [4 1 0 1 0 4 4]
Check if array's values are equal: False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [51]:
vec=np.random.random(6)
print("random values:\n",vec)
vec[vec.argmax()] = 0
print("After replacing maximum number with 0:\n",vec)

random values:
 [0.65161962 0.87500454 0.93530877 0.48961752 0.52312052 0.88211101]
After replacing maximum number with 0:
 [0.65161962 0.87500454 0.         0.48961752 0.52312052 0.88211101]


# 9. How to print all the values of an array?

In [54]:
val=np.zeros((5,5))
print("print all vales in array:\n",val)

print all vales in array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [59]:
orgi = np.random.rand(5, 10)
print("Original matrix:\n",orgi)
meansub =orgi-orgi.mean(axis=1, keepdims=True)
print("Subtracting the mean of each row:\n",meansub)

Original matrix:
 [[0.02951505 0.06358913 0.04329458 0.45371697 0.59927469 0.60378073
  0.12766281 0.40612948 0.34267737 0.88188681]
 [0.55216444 0.86529591 0.54776315 0.01060513 0.32274638 0.94158509
  0.49262848 0.18380539 0.20870952 0.62242442]
 [0.43749683 0.96515262 0.15909489 0.68501137 0.75309747 0.21304069
  0.09296191 0.51029834 0.1373448  0.54439933]
 [0.56893619 0.38472116 0.91057635 0.7390995  0.34719104 0.52413716
  0.50993918 0.63575504 0.71328713 0.6200302 ]
 [0.60914977 0.16536372 0.98779967 0.84154694 0.02444412 0.67198585
  0.54282444 0.37559127 0.85879121 0.94125359]]
Subtracting the mean of each row:
 [[-0.32563771 -0.29156363 -0.31185818  0.09856421  0.24412193  0.24862796
  -0.22748996  0.05097672 -0.01247539  0.52673405]
 [ 0.07739165  0.39052312  0.07299035 -0.46416766 -0.15202641  0.4668123
   0.01785569 -0.2909674  -0.26606327  0.14765162]
 [-0.012293    0.51536279 -0.29069494  0.23522155  0.30330765 -0.23674913
  -0.35682792  0.06050851 -0.31244502  0.0946095

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [62]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 3. 4. 3. 4. 4. 3. 4. 1. 2.]


# 12.How to get the diagonal of a dot product?

In [73]:
a = np.array([[5,7],[8,9]]) 
print("First Matrix:\n",a)
b= np.array([[5,7],[8,9]]) 
print("Second Matrix:\n",b)
print("Diagonal of a dot product:",np.diag(np.dot(a,b)))

First Matrix:
 [[5 7]
 [8 9]]
Second Matrix:
 [[5 7]
 [8 9]]
Diagonal of a dot product: [ 81 137]


# 13.How to find the most frequent value in an array?

In [76]:
getvalues=np.random.randint(0,20,20)
print(getvalues)
mostFreq=np.bincount(getvalues).argmax()
print("Most Frequent Value:",mostFreq)

[ 4  3  5  6 19 11 11  1 14 14 17 18 11  2 14  6  6  8 19 11]
Most Frequent Value: 11


# 14.How to get the n largest values of an array

In [82]:
values=np.array([5,7,0,999,10000,20039039])
print("Elements in array:",values)
n = 3
large = values[np.argsort(values)[-n:]]
print("3 Largest values of array values:",large)

Elements in array: [       5        7        0      999    10000 20039039]
3 Largest values of array values: [     999    10000 20039039]


# 15.How to create a record array from a regular array?

In [86]:
a = np.array(['New','Machine'])
b = np.array(['Language','Learning'])
c = np.array([2,1])
record=np.core.records.fromarrays([a,b])
print(record[0])
print(record[1])

('New', 'Language')
('Machine', 'Learning')
